[package]
name = "clippin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
env_logger = "0.11.5"
fs_extra = "1.3.0"
indicatif = "0.17.9"
log = "0.4.22"
